---

- name: playbook for creating Fabric Extenders
  hosts: apic1
  connection: local
  gather_facts: no

  tasks:

    # PREP

    #- name: ensure tenant exists
    #  aci_tenant: name=ACILab descr='tenant by Ansible' host={{ inventory_hostname }} username={{ user }} password={{ pass }}

    # TESTING APP NET PROFILES AND EPGS

    - name: Create FEX Profile
      aci-rest:
         host: "{{ inventory_hostname }}"
         username: "{{ user }}"
         password: "{{ pass }}"
         
         method: post
         path: /api/mo/uni.json
         content:
           {
   "infraFexP": {
      "attributes": {
         "dn": "uni/infra/fexprof-LEAF101_FEX101",
         "name": "LEAF101_FEX101",
         "rn": "fexprof-LEAF101_FEX101",
         "status": "created,modified"
      },
      "children": [
         {
            "infraFexBndlGrp": {
               "attributes": {
                  "dn": "uni/infra/fexprof-LEAF101_FEX101/fexbundle-LEAF101_FEX101",
                  "name": "LEAF101_FEX101",
                  "rn": "fexbundle-LEAF101_FEX101",
                  "status": "created,modified"
               },
               "children": []
            }
         }
      ]
   }
}

    - name: Create FEX-NIF Uplinks
      aci-rest:
         host: "{{ inventory_hostname }}"
         username: "{{ user }}"
         password: "{{ pass }}"
         
         method: post
         path: /api/mo/uni.json
         content:
{
   "infraHPortS": {
      "attributes": {
         "dn": "uni/infra/accportprof-LEAF101_PROF/hports-LEAF101_FEX101_NIF-typ-range",
         "name": "LEAF101_FEX101_NIF",
         "rn": "hports-LEAF101_FEX101_NIF-typ-range",
         "status": "created,modified"
      },
      "children": [
         {
            "infraPortBlk": {
               "attributes": {
                  "dn": "uni/infra/accportprof-LEAF101_PROF/hports-LEAF101_FEX101_NIF-typ-range/portblk-block2",
                  "fromPort": "9",
                  "toPort": "10",
                  "name": "block2",
                  "rn": "portblk-block2",
                  "status": "created,modified"
               },
               "children": []
            }
         },
         {
            "infraRsAccBaseGrp": {
               "attributes": {
                  "tDn": "uni/infra/fexprof-LEAF101_FEX101/fexbundle-LEAF101_FEX101",
                  "status": "created,modified"
               },
               "children": []
            }
         }
      ]
   }
}

    - name: Make a single 1GB port ready on the Fabric Extnder ready for static EGP binding HIF port
    
      aci-rest:
         host: "{{ inventory_hostname }}"
         username: "{{ user }}"
         password: "{{ pass }}"
         
         method: post
         path: /api/mo/uni.json
         content:
{
   "infraHPortS": {
      "attributes": {
         "dn": "uni/infra/fexprof-LEAF101_FEX101/hports-Port101-101-1-1-typ-range",
         "name": "Port101-101-1-1",
         "rn": "hports-Port101-101-1-1-typ-range",
         "status": "created,modified"
      },
      "children": [
         {
            "infraPortBlk": {
               "attributes": {
                  "dn": "uni/infra/fexprof-LEAF101_FEX101/hports-Port101-101-1-1-typ-range/portblk-block2",
                  "name": "block2",
                  "rn": "portblk-block2",
                  "status": "created,modified"
               },
               "children": []
            }
         },
         {
            "infraRsAccBaseGrp": {
               "attributes": {
                  "tDn": "uni/infra/funcprof/accportgrp-AccessPort_1GB_POL",
                  "status": "created,modified"
               },
               "children": []
            }
         }
      ]
   }
}

    - name: Static EGP binding access port vlan 3001
    
      aci-rest:
         host: "{{ inventory_hostname }}"
         username: "{{ user }}"
         password: "{{ pass }}"
         
         method: post
         path: api/node/mo/uni/tn-Josh_C_Nutanix/ap-Josh_C_Nutanix_APP/epg-Josh_C_Prod_EPG.json
         content:
{
   "fvRsPathAtt": {
      "attributes": {
         "encap": "vlan-3001",
         "mode": "native",
         "tDn": "topology/pod-1/paths-101/extpaths-101/pathep-[eth1/1]",
         "status": "created"
      },
      "children": []
   }
}
         
         

  