- name: Create Fabric Extender
  hosts: all
  connection: local
  gather_facts: no


  tasks:
    - name: Create a FEX Profile
      aci_rest:
         hostname: "{{ inventory_hostname }}"
         username: "admin"
         password: "Worldcom1"
         validate_certs: no
         method: post
         path: /api/mo/uni.json
         content:
           {
   "infraFexP": {
      "attributes": {
         "dn": "uni/infra/fexprof-LEAF102_FEX101",
         "name": "LEAF102_FEX101",
         "rn": "fexprof-LEAF102_FEX101",
         "status": "created,modified"
      },
      "children": [
         {
            "infraFexBndlGrp": {
               "attributes": {
                  "dn": "uni/infra/fexprof-LEAF102_FEX101/fexbundle-LEAF102_FEX101",
                  "name": "LEAF102_FEX101",
                  "rn": "fexbundle-LEAF102_FEX101",
                  "status": "created,modified"
               },
               "children": []
            }
         }
      ]
   }
}

    - name: Create FEX NIF Uplink
      aci_rest:
         hostname: "{{ inventory_hostname }}"
         username: "admin"
         password: "Worldcom1"
         validate_certs: no
         method: post
         path: /api/mo/uni.json
         content:
           {
   "infraHPortS": {
      "attributes": {
         "dn": "uni/infra/accportprof-LEAF102_PROF/hports-LEAF102_FEX101_NIF-typ-range",
         "name": "LEAF102_FEX101_NIF",
         "rn": "hports-LEAF102_FEX101_NIF-typ-range",
         "status": "created,modified"
      },
      "children": [
         {
            "infraPortBlk": {
               "attributes": {
                  "dn": "uni/infra/accportprof-LEAF102_PROF/hports-LEAF102_FEX101_NIF-typ-range/portblk-block2",
                  "fromPort": "9",
                  "toPort": "10",
                  "name": "block2",
                  "rn": "portblk-block2",
                  "status": "created,modified"
               },
               "children": []
            }
         },
         {
            "infraRsAccBaseGrp": {
               "attributes": {
                  "tDn": "uni/infra/fexprof-LEAF102_FEX101/fexbundle-LEAF102_FEX101",
                  "status": "created,modified"
               },
               "children": []
            }
         }
      ]
   }
}

    
